version: "3.9"

services:
    postgres:
        hostname: mysql
        image: mysql:latest
        ports:
            - ${DB_PORT}:3306
        # volumes:
        #     - ./volumes/mysql:/var/lib/mysql/data
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
